services:
  database:
    image: postgres:latest
    container_name: ai_database
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chat_db
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    container_name: ai_backend
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      OLLAMA_URL: http://host.docker.internal:11434  # Mengarahkan ke Ollama di host

  frontend:
    image: nginx:alpine
    container_name: ai_frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "80:80"
